#!/bin/bash


function fatal(){
	printf "\033[1;37mcvg++:\033[1;31m fatal error:\033[0;97m $1\n"
}



if [ "$2" == '' ];then
	fatal "no target OS provided"
	echo "compilation terminated."
	exit 1
fi

if [ ! -f "$1" ];then
	fatal "$1: No such file or directory"
	echo "compilation terminated."
	exit 1
fi

export "$2"

set $1 $3 $4 $5 $6 $7 $8 $9 &> /dev/null

if [ "$target" == "windows" ];then
	export compiler="x86_64-w64-mingw32-cpp"
elif [ "$target" == "linux" ];then
	export compiler="g++"
fi
echo "$compiler"

#$compiler -Wall -z execstack -fno-stack-protector $@
