#!/bin/bash


function fatal(){
	printf "\033[1;37mcvg++:\033[1;31m fatal error:\033[0;97m $1\n"
}


if [ "$2" == '' ];then
	fatal "no target OS provided"
	echo "compilation terminated."
	exit 1
fi

if [ ! -f "$1" ];then
	fatal "$1: No such file or directory"
	echo "compilation terminated."
	exit 1
fi

export "$2"

set $1 $3 $4 $5 $6 $7 $8 $9 &> /dev/null

if [ "$target" == "windows" ] || [ "$target" == "win64" ];then
	export compiler="x86_64-w64-mingw32-g++"
	export striper="x86_64-w64-mingw32-strip"
	CVPath="CVWindows"
elif [ "$target" == "win32" ];then
	export compiler="i686-w64-mingw32-g++"
	export striper="i686-w64-mingw32-strip"
	CVPath="CVWindows"
elif [ "$target" == "linux" ];then
	export compiler="g++"
	export striper="strip"
	CVPath="CVLinux"
else fatal "target OS unknown"; echo "compilation terminated."; exit 1;

fi

$compiler -Wall -static -I ~/.CVenom/$CVPath/ $@
$striper $1
