#!/bin/bash

function updater(){
	rm ~/.CVenom -rif &> /dev/null
	cd /tmp
	rm /tmp/CVenom -rif
	git clone https://github.com/Mahmoud7Osman/CVenom
	cd CVenom/Setup
	bash setup.sh
}
function uninstaller(){
	rm ~/.CVenom -rif &> /dev/null
}


if [ "$1" == "update" ];then
	updater
elif [ "$1" == "uninstall" ];then
	uninstaller
else printf "cvenom: execute with --help for help\n"
fi
